api: adsf
api-version: 1.12.2
name: ModifyMenuV3
version: 1,0
main: me.olafgoud.ModifyMenuMain
commands:
  modifyatt:
    usage: /modifyatt
  enchmenu:
    usage: /enchmenu
  modifygetset:
    usage: /modifygetset
  modifyname:
    usage: /modifyname
  modifyglow:
    usage: /modifyglow
  modifylore:
    usage: /modifylore
  modifymore:
    usage: /modifymore
  modifyaddtag:
    usage: /modifyaddtag
  modifysetcolor:
    usage: /modifysetcolor